### ISSUE TITLE
pls open

### ISSUE THREAD

**Issue by theprogrammingking** [Shashwat-Sahu/Microsoft-Teams-Clone#3]
hey shashwat-sahu how did you deploy and can i clone this project?
you used mongodb right guid me how to cheange db to my credentials i really appreciate if you answer

thanks,
pranav

**Comment by Shashwat-Sahu** [comment]
Yes you can clone it and star it if you wish.
Apart from this Go to Mongo DB ,create account and then collection with name MicrosoftTeams. Paste the provided URI to .env

**Comment by theprogrammingking** [comment]
anyways where is the env file located for easier can you please put setup video pls 

thanks,
theprogrammingKing

**Comment by theprogrammingking** [comment]
actually the firebase and auth with the viddoe i fyou can do it?!
